# Generated by Django 6.0.1 on 2026-02-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app2', '0002_tablestock_low_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('acount_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_to_ac_type', to='client_app2.account_type')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit (Money In)'), ('credit', 'Credit (Money Out)')], max_length=10, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='client_app2.account')),
            ],
        ),
    ]
