# Generated by Django 6.0.1 on 2026-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app2', '0003_account_type_account_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
