from django.db import models

# Create your models here.

class TableCustomer(models.Model):
    name=models.CharField(max_length=100, null=True)
    phone=models.IntegerField(null=True)
    email=models.EmailField(max_length=50,null=True)
    address=models.TextField(null=True)

class TableChuridar(models.Model):
    customer_name=models.CharField(null=True, max_length=100)
    flength=models.CharField(max_length=100,null=True)
    point=models.CharField(max_length=100,null=True)
    tuck=models.CharField(max_length=100,null=True)
    yoke=models.CharField(max_length=100,null=True)
    pw=models.CharField(max_length=100,null=True)
    slit=models.CharField(max_length=100,null=True)
    shoulder=models.CharField(max_length=100,null=True)
    sl=models.CharField(max_length=100,null=True)
    sr=models.CharField(max_length=100,null=True)
    muscle=models.CharField(max_length=100,null=True)
    ah=models.CharField(max_length=100,null=True)
    apf=models.CharField(max_length=100,null=True)
    apb=models.CharField(max_length=100,null=True)
    chest=models.CharField(max_length=100,null=True)
    bust=models.CharField(max_length=100,null=True)
    waist1=models.CharField(max_length=100,null=True)
    hip=models.CharField(max_length=100,null=True)
    seat=models.CharField(max_length=100,null=True)
    neckf=models.CharField(max_length=100,null=True)
    neckb=models.CharField(max_length=100,null=True)
    neckw=models.CharField(max_length=100,null=True)
    waist2=models.CharField(max_length=100,null=True)
    length=models.CharField(max_length=100,null=True)
    width=models.CharField(max_length=100,null=True)
    kneel=models.CharField(max_length=100,null=True)
    kneer=models.CharField(max_length=100,null=True)
    thighl=models.CharField(max_length=100,null=True)
    thighr=models.CharField(max_length=100,null=True)
    downf=models.CharField(max_length=100,null=True)

class TableSaree(models.Model):
    customer_name = models.CharField(null=True, max_length=100)
    flength = models.CharField(max_length=100, null=True)
    point = models.CharField(max_length=100, null=True)
    tuck = models.CharField(max_length=100, null=True)
    pw = models.CharField(max_length=100, null=True)
    shoulder = models.CharField(max_length=100, null=True)
    sl = models.CharField(max_length=100, null=True)
    sr = models.CharField(max_length=100, null=True)
    muscle = models.CharField(max_length=100, null=True)
    ah = models.CharField(max_length=100, null=True)
    apf = models.CharField(max_length=100, null=True)
    apb = models.CharField(max_length=100, null=True)
    chest = models.CharField(max_length=100, null=True)
    bust = models.CharField(max_length=100, null=True)
    waist1 = models.CharField(max_length=100, null=True)
    neckf = models.CharField(max_length=100, null=True)
    neckb = models.CharField(max_length=100, null=True)
    neckw = models.CharField(max_length=100, null=True)
    waist2 = models.CharField(max_length=100, null=True)
    length1 = models.CharField(max_length=100, null=True)
    dwidth = models.CharField(max_length=100, null=True)
    kneel = models.CharField(max_length=100, null=True)
    kneer = models.CharField(max_length=100, null=True)
    seat = models.CharField(max_length=100, null=True)
    waist3 = models.CharField(max_length=100, null=True)
    length2 = models.CharField(max_length=100, null=True)
    pallu = models.CharField(max_length=100, null=True)


