# Generated by Django 6.0.1 on 2026-01-31 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableChuridar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=100, null=True)),
                ('length1', models.CharField(max_length=100, null=True)),
                ('point', models.CharField(max_length=100, null=True)),
                ('tuck', models.CharField(max_length=100, null=True)),
                ('yoke', models.CharField(max_length=100, null=True)),
                ('pw', models.CharField(max_length=100, null=True)),
                ('slit', models.CharField(max_length=100, null=True)),
                ('shoulder', models.CharField(max_length=100, null=True)),
                ('sl', models.CharField(max_length=100, null=True)),
                ('sr', models.CharField(max_length=100, null=True)),
                ('muscle', models.CharField(max_length=100, null=True)),
                ('ah', models.CharField(max_length=100, null=True)),
                ('apf', models.CharField(max_length=100, null=True)),
                ('apb', models.CharField(max_length=100, null=True)),
                ('chest', models.CharField(max_length=100, null=True)),
                ('bust', models.CharField(max_length=100, null=True)),
                ('hip', models.CharField(max_length=100, null=True)),
                ('seat', models.CharField(max_length=100, null=True)),
                ('neckf', models.CharField(max_length=100, null=True)),
                ('neckb', models.CharField(max_length=100, null=True)),
                ('neckw', models.CharField(max_length=100, null=True)),
                ('waist', models.CharField(max_length=100, null=True)),
                ('length2', models.CharField(max_length=100, null=True)),
                ('width', models.CharField(max_length=100, null=True)),
                ('kneel', models.CharField(max_length=100, null=True)),
                ('kneer', models.CharField(max_length=100, null=True)),
                ('thighl', models.CharField(max_length=100, null=True)),
                ('Thighr', models.CharField(max_length=100, null=True)),
                ('Downf', models.CharField(max_length=100, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.tablecustomer')),
            ],
        ),
    ]
