# Generated by Django 6.0.1 on 2026-01-31 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('due_date', models.DateField(null=True)),
                ('cloth_type', models.CharField(max_length=100, null=True)),
                ('item', models.CharField(max_length=100, null=True)),
                ('lining', models.CharField(max_length=100, null=True)),
                ('bottom', models.CharField(max_length=100, null=True)),
                ('locking', models.CharField(max_length=100, null=True)),
                ('pattern', models.CharField(max_length=100, null=True)),
                ('sareefall_type', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('stitching_charges', models.IntegerField(null=True)),
                ('additional_charges', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('advance_paid', models.IntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.tablecustomer')),
            ],
        ),
    ]
