# Generated by Django 6.0.1 on 2026-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_tableorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='customer',
        ),
        migrations.AddField(
            model_name='tableorders',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tableorders',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tableorders',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tableorders',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tableorders',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
