# Generated by Django 6.0.1 on 2026-01-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_tablechuridar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='name',
            new_name='customer',
        ),
    ]
