# Generated by Django 6.0.1 on 2026-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_remove_tableorders_customer_tableorders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
