# Generated by Django 6.0.1 on 2026-01-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_rename_name_tablechuridar_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='full',
            new_name='flength',
        ),
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='length1',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='length2',
            new_name='waist1',
        ),
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='waist',
            new_name='waist2',
        ),
    ]
