# Generated by Django 6.0.1 on 2026-02-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_tableorders_customer_id'),
        ('client_app', '0004_rename_number_tablestaffs_phone'),
    ]

    operations = [
    ]
