# Generated by Django 6.0.1 on 2026-02-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_tableorders_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
