# Generated by Django 6.0.1 on 2026-01-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_rename_full_tablechuridar_flength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='Downf',
            new_name='downf',
        ),
        migrations.RenameField(
            model_name='tablechuridar',
            old_name='Thighr',
            new_name='thighr',
        ),
    ]
