# Generated by Django 6.0.1 on 2026-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_merge_20260202_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='order_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
