# Generated by Django 6.0.1 on 2026-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_rename_downf_tablechuridar_downf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablechuridar',
            name='customer',
        ),
        migrations.AddField(
            model_name='tablechuridar',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
