# Generated by Django 6.0.1 on 2026-02-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_merge_20260202_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(null=True)),
                ('fixed_salary', models.FloatField(null=True)),
                ('total_overtime', models.FloatField(default=0)),
                ('total_salary', models.FloatField(null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.tablestaffs')),
            ],
        ),
    ]
