# Generated by Django 6.0.1 on 2026-02-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_tablesalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablesalary',
            old_name='month',
            new_name='date',
        ),
    ]
