# Generated by Django 6.0.1 on 2026-02-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_remove_tablechuridar_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSaree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('flength', models.CharField(max_length=100, null=True)),
                ('point', models.CharField(max_length=100, null=True)),
                ('tuck', models.CharField(max_length=100, null=True)),
                ('pw', models.CharField(max_length=100, null=True)),
                ('shoulder', models.CharField(max_length=100, null=True)),
                ('sl', models.CharField(max_length=100, null=True)),
                ('sr', models.CharField(max_length=100, null=True)),
                ('muscle', models.CharField(max_length=100, null=True)),
                ('ah', models.CharField(max_length=100, null=True)),
                ('apf', models.CharField(max_length=100, null=True)),
                ('apb', models.CharField(max_length=100, null=True)),
                ('chest', models.CharField(max_length=100, null=True)),
                ('bust', models.CharField(max_length=100, null=True)),
                ('waist1', models.CharField(max_length=100, null=True)),
                ('neckf', models.CharField(max_length=100, null=True)),
                ('neckb', models.CharField(max_length=100, null=True)),
                ('neckw', models.CharField(max_length=100, null=True)),
                ('waist2', models.CharField(max_length=100, null=True)),
                ('length1', models.CharField(max_length=100, null=True)),
                ('dwidth', models.CharField(max_length=100, null=True)),
                ('kneel', models.CharField(max_length=100, null=True)),
                ('kneer', models.CharField(max_length=100, null=True)),
                ('seat', models.CharField(max_length=100, null=True)),
                ('waist3', models.CharField(max_length=100, null=True)),
                ('length2', models.CharField(max_length=100, null=True)),
                ('pallu', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
