# Generated by Django 6.0.1 on 2026-02-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_rename_month_tablesalary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesalary',
            name='payment_date',
        ),
    ]
