# Generated by Django 6.0.1 on 2026-02-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_tableorders_status'),
        ('client_app', '0007_tablesaree'),
    ]

    operations = [
    ]
