# Generated by Django 6.0.1 on 2026-02-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_remove_tablesalary_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesalary',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.tablestaffs'),
        ),
        migrations.CreateModel(
            name='TableOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_date', models.DateField(null=True)),
                ('extra_hours', models.FloatField(null=True)),
                ('ot_amount', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.tablesalary')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.tablestaffs')),
            ],
        ),
    ]
