# Generated by Django 6.0.1 on 2026-02-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_alter_tablesalary_staff_tableovertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestaffs',
            name='fixed_salary',
            field=models.FloatField(default=0),
        ),
    ]
