# Generated by Django 6.0.1 on 2026-02-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_tablestaffs_fixed_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablestaffs',
            old_name='fixed_salary',
            new_name='monthly_salary',
        ),
    ]
