# Generated by Django 6.0.1 on 2026-02-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_rename_fixed_salary_tablestaffs_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesalary',
            name='salary_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
