# Generated by Django 6.0.1 on 2026-02-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_tableorders_order_id'),
        ('client_app', '0012_tablesalary_salary_month'),
    ]

    operations = [
    ]
