# Generated by Django 6.0.1 on 2026-02-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0013_merge_20260204_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableovertime',
            name='status',
        ),
    ]
