# Generated by Django 6.0.1 on 2026-02-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_remove_tableovertime_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.FloatField(default=0, null=True)),
                ('pending', models.FloatField(default=0, null=True)),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.tablesalary')),
            ],
        ),
    ]
