# Generated by Django 6.0.1 on 2026-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_tableextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecustomer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tableorders',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tablestaffs',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
