# Generated by Django 6.0.1 on 2026-02-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0016_alter_tablecustomer_phone_alter_tableorders_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='cloth_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
