# Generated by Django 6.0.1 on 2026-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0017_tableorders_cloth_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorders',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
