# Generated by Django 6.0.1 on 2026-02-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0018_alter_tableorders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='image',
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client_app.tableorders')),
            ],
        ),
    ]
