# Generated by Django 6.0.1 on 2026-02-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0019_remove_tableorders_image_orderimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderImage',
            new_name='TableOrderImage',
        ),
    ]
